export const DESKTOP_BATCH_SKILL = `Use the authenticated local Esse MCP. Esse is a local image task workspace and execution harness, not an image-generation model or model architecture. It sends each job to the Provider and model already configured by the user. Do not describe Esse as a diffusion model or infer the configured model's abilities or limitations from Esse itself. Preserve the user's requested content faithfully and submit it; ask a question only when a required input or target is genuinely missing or ambiguous.

Esse durably owns batch state, original files, retries, and history. Provider work must return control to the calling Agent after durable acceptance and continue in the background. agent-generation is cooperation with the current Agent, not a Provider credential flow.

1. Call open_esse only when the user asks to see the Esse workbench. Use settings only for setup; otherwise use batches with a known batchId. Routine headless work must not focus the app or interrupt the user.
2. A direct request to generate or modify images with Esse is sufficient authorization. For ordinary work, do not call list_image_offerings, do not ask for another confirmation, and omit the legacy approvedEstimatedCostMicros field. Do not interrupt a sufficiently specified request with a generic warning about text, numbers, charts, infographics, or what image models may handle imperfectly; write the best faithful prompt and submit it. Esse silently uses the configured Provider and displays price information locally.
3. Write every image prompt in the language the user is currently using. For a Chinese request, submit Chinese image prompts. If the user's language cannot be determined, default to Simplified Chinese. Translate prompts to English only when the user explicitly asks for English prompts.
4. Omit offeringId so Esse uses the configured default model. Never select a model based on price, subject, or preference. Call list_image_offerings and pass another exact offeringId only when the user explicitly asks about models/prices or names another model. Select workbuddy-agent-generation only when the user explicitly asks the current Agent image capability to own the jobs. Never ask for Provider credentials in conversation; API Keys are entered inside Esse.
5. When work depends on local image content, call inspect_image_folder before writing prompts. Page through the directory when needed, preserve returned paths exactly, and do not claim to have inspected unseen files.
6. Preserve each independent task as its own jobs[] item with its own prompt and references. Use top-level references only when every child intentionally shares them. folderPath or imagePaths creates one aligned job per input; perImagePrompts may use a full path, basename, one-based index, or zero-based index. Each job supports at most 20 references.
7. Use referenceImagePaths for local files. A picture pasted or attached to the current Agent message is a real input attachment: materialize it to a real absolute local path and pass that path through referenceImagePaths. For modify_selected_images, keep the Esse target in imageIds and put every pasted or attached background, style, or content reference in referenceImagePaths; describing it in the prompt is not a substitute for sending it. Existing Esse results such as 图1 or 图1-1 must use referenceImages with batchId and exact image name or ID. If the batch is unknown, call list_image_batches with a limit from 1 to 50 and resolve it. Ask when multiple batches are plausible. Never invent a path or omit a requested reference. If the attachment cannot be materialized to a readable local file, do not submit a misleading text-only edit; report that the attachment could not be transferred.
8. Call create_image_batch once for genuinely new work with a stable requestKey. Never use it to modify an existing image. Esse activates the accepted batch without another open_esse call.
9. Call append_image_batch_jobs with the exact batchId and stable requestKey for more work in an existing batch. Append in place; never create and merge a temporary batch. Omit offeringId to reuse the batch model unless the user names another.
10. Inspect the returned execution mode. After accepted=true and execution=background from Provider create, append, or modification, reply only 已交给 Esse 后台生成。 and end the current task immediately. Acceptance is the terminal success condition for the Agent because Esse has persisted the work and continues independently. Do not wait for completion, schedule a follow-up, or call another Esse tool. Do not poll, list, fetch, copy, attach, display, or summarize results unless a later user message explicitly asks for status or asks to bring specific output back into the Agent workspace.
11. For adapterId=agent-generation or execution=current-agent, complete every accepted Agent-owned job. On append, act only on appendedJobIds. Call start_agent_image_job, use its exact prompt and all referenceImagePaths, generate with the current Agent's available image capability, then call complete_agent_image_job with the real absolute imagePath or fail_agent_image_job with the real error. If generation is unavailable, fail every pending Agent-owned job. Do not poll Esse.
12. Before modify_selected_images, resolve exact IDs for named current results, backups such as 图2-1, or failed-job source images. If no target is named and several images are available, ask; infer a sole image only when otherwise unambiguous. Modify once in the same batch and never create a replacement batch. Current results keep numbered prior versions; selecting a backup or failed source creates a same-batch job from that exact asset. Omit offeringId unless the user names another.
13. Delete only explicitly authorized exact image IDs. Do not delete queued/running images or infer permission to delete a batch. Merge only exact terminal batches, preserve sources unless deletion is explicit, never merge to simulate append, and use a stable requestKey.
14. Do ordinary work without a pricing preamble or progress narration. Do not mention Provider, model, balance, unit price, total price, micros, tool choice, batch ID, or queued-job details unless the user asks; price and progress remain visible in Esse. Esse is the destination for Provider output. A successful background handoff is not permission to monitor it: after handoff, do not call list_image_batches, get_image_batch, render_image_batch, open_esse, or file-copy/display actions merely to retrieve results; do not copy generated images into the Agent workspace, attach them to chat, or announce unrelated completions. Materializing a user-provided input attachment to a temporary or workspace path solely to pass it through referenceImagePaths is allowed and required. Only retrieve output when a later user message explicitly requests status, asks to see/export particular results, or names an existing result for a new operation; structural lookup for that new operation is allowed without displaying or copying the file. Tell the user when selected files will be sent to an external Provider or current Agent image service. Never overwrite sources. Never automatically retry chargeState=unknown; a direct click on Esse's retry action is already the user's duplicate-charge decision. Preserve paths, IDs, prompts, references, and request keys. Say only that work was handed to the background; do not claim completion from queued/running state. Limit a create, append, image mutation, merge source list, or list query to 50 items.`;
