import { AUTHORIZED_WORKFLOW_POLICY } from './workflow-policy';

export const DESKTOP_BATCH_SKILL = `Use the authenticated local Esse MCP. Esse is a local image task workspace and execution harness, not an image-generation model or model architecture. It sends each job to the Provider and model already configured by the user. Do not describe Esse as a diffusion model or infer the configured model's abilities or limitations from Esse itself. Preserve the user's requested content faithfully and submit it; ask a question only when a required input or target is genuinely missing or ambiguous.

Esse durably owns batch state, original files, retries, and history. Provider work must return control to the calling Agent after durable acceptance and continue in the background. agent-generation is cooperation with the current Agent, not a Provider credential flow.

1. Call open_esse only when the user asks to see the Esse workbench. Use settings only for setup; otherwise use batches with a known batchId. Routine headless work must not focus the app or interrupt the user.
2. A direct request to generate or modify images with Esse is sufficient authorization. For ordinary work, do not call list_image_offerings, do not ask for another confirmation, and omit the legacy approvedEstimatedCostMicros field. Do not interrupt a sufficiently specified request with a generic warning about text, numbers, charts, infographics, or what image models may handle imperfectly; write the best faithful prompt and submit it. Esse silently uses the configured Provider and displays price information locally.
3. Write every image prompt in the language the user is currently using. For a Chinese request, submit Chinese image prompts. If the user's language cannot be determined, default to Simplified Chinese. Translate prompts to English only when the user explicitly asks for English prompts.
4. Omit offeringId so Esse uses the configured default model. Never select a model based on price, subject, or preference. Call list_image_offerings and pass another exact offeringId only when the user explicitly asks about models/prices or names another model. Select workbuddy-agent-generation only when the user explicitly asks the current Agent image capability to own the jobs. Never ask for Provider credentials in conversation; API Keys are entered inside Esse.
5. When work depends on local image content, call inspect_image_folder before writing prompts. Page through the directory when needed, preserve returned paths exactly, and do not claim to have inspected unseen files.
6. Preserve each independent task as its own jobs[] item with its own prompt and references. Use top-level references only when every child intentionally shares them. folderPath or imagePaths creates one aligned job per input; perImagePrompts may use a full path, basename, one-based index, or zero-based index. Each job supports at most 20 references.
7. Use referenceImagePaths for local files. A picture pasted or attached to the current Agent message is a real input attachment: materialize it to a real absolute local path and pass that path through referenceImagePaths. For modify_selected_images, keep the Esse target in imageIds and put every pasted or attached background, style, or content reference in referenceImagePaths; describing it in the prompt is not a substitute for sending it. Existing Esse results such as 图1 or 图1-1 must use referenceImages with batchId and exact image name or ID. If the batch is unknown, call list_image_batches with a limit from 1 to 50 and resolve it. Ask when multiple batches are plausible. Never invent a path or omit a requested reference. If the attachment cannot be materialized to a readable local file, do not submit a misleading text-only edit; report that the attachment could not be transferred.
8. Call create_image_batch once for genuinely new work with a stable requestKey. Never use it to modify an existing image. Esse activates the accepted batch without another open_esse call.
9. Call append_image_batch_jobs with the exact batchId and stable requestKey for more work in an existing batch. Append in place; never create and merge a temporary batch. Omit offeringId to reuse the batch model unless the user names another.
10. Inspect the returned execution mode and preserve the returned batch/job handles. For execution=background, follow this authorized continuation policy: ${AUTHORIZED_WORKFLOW_POLICY}
11. For adapterId=agent-generation or execution=current-agent, complete every accepted Agent-owned job. On append, act only on appendedJobIds. Call start_agent_image_job and use its exact prompt and all referenceImagePaths. One start call is exactly one outbound image-generation request: never combine reference paths from other batch jobs into it. Independent jobs may run concurrently, but their prompts, references, and request-size checks stay isolated per job. Then call complete_agent_image_job with the real absolute imagePath or fail_agent_image_job with the real error. If generation is unavailable, fail every pending Agent-owned job. Agent job callbacks update Esse directly; query the exact batch only when needed for already-authorized verification.
12. Before modify_selected_images, resolve exact IDs for named current results, backups such as 图2-1, or failed-job source images. If no target is named and several images are available, ask; infer a sole image only when otherwise unambiguous. Modify once in the same batch and never create a replacement batch. Current results keep numbered prior versions; selecting a backup or failed source creates a same-batch job from that exact asset. Omit offeringId unless the user names another.
13. Delete only explicitly authorized exact image IDs. Do not delete queued/running images or infer permission to delete a batch. Merge only explicitly requested exact terminal batches with a stable requestKey; it moves jobs and history into the target and removes the source batches after durable acceptance. Never merge to simulate append.
14. Keep ordinary price details in Esse unless the user asks or they are needed to enforce the original budget. Give task-relevant progress and an honest final acceptance summary; never claim completion from queued/running state or background acceptance. Retrieve and display only results within the existing task authorization. Materialize real input attachments before passing referenceImagePaths, and report missing inputs honestly. Tell the user when selected files will be sent to an external Provider or current Agent image service. Never overwrite sources. A direct click on Esse retry is the user decision for that exact request, not permission for further retries. Preserve paths, IDs, prompts, references, request keys, and waiting deadlines. Limit a create, append, image mutation, merge source list, or list query to 50 items.`;
